// Revue des mots interdits des régimes (03/10/2026, après « cuscús » étiqueté sans gluten) : pour chaque aliment
// interdit courant, ses noms en français, en anglais et en espagnol, au singulier et au pluriel, doivent être repérés
// par le serveur (dietWordInName). Une ligne par aliment ; une ligne ajoutée par mot ajouté aux listes. En regard,
// des aliments permis qui ne doivent jamais être repérés (faux positifs). Mots écartés car ambigus : « glace » (glaçons,
// sucre glace, demi-glace), « rib » (« celery ribs »), « gravy » (sauce aux champignons), « bar » (« granola bar »),
// « coque » (coquillettes), « lieu » seul (« au lieu de ») : seules leurs formes sans ambiguïté sont contrôlées.

import { assertEquals } from 'jsr:@std/assert@1';
import { dietWordInName, dietWordInText, type StrictDiet } from './recipes.ts';

// [régime, aliment, noms : fr singulier, fr pluriel, en singulier, en pluriel, es singulier, es pluriel]
const FORBIDDEN: [StrictDiet, string, string[]][] = [
  // ---------- Sans gluten ----------
  ['gluten-free', 'blé', ['blé', 'blés', 'wheat', 'wheat berries', 'trigo', 'trigos']],
  ['gluten-free', 'orge', ['orge', 'orge perlé', 'barley', 'pearl barley', 'cebada', 'cebadas']],
  ['gluten-free', 'seigle', ['seigle', 'pain de seigle', 'rye', 'rye flakes', 'centeno', 'centenos']],
  ['gluten-free', 'épeautre', ['épeautre', 'épeautres', 'spelt', 'spelt flakes', 'espelta', 'espeltas']],
  ['gluten-free', 'avoine', ['avoine', "flocons d'avoine", 'oat', 'oats', 'avena', 'copos de avena']],
  ['gluten-free', 'couscous', ['couscous', 'graines de couscous', 'couscous', 'couscous grains', 'cuscús', 'cuscuses']],
  ['gluten-free', 'boulgour', ['boulgour', 'boulgours', 'bulgur', 'bulgur wheat', 'bulgur', 'trigo bulgur']],
  ['gluten-free', 'semoule', ['semoule', 'semoules', 'semolina', 'semolinas', 'sémola', 'sémolas']],
  ['gluten-free', 'pain', ['pain', 'pains', 'bread', 'breads', 'pan', 'panes']],
  ['gluten-free', 'pâtes', ['pâtes', 'pâtes fraîches', 'pasta', 'pastas', 'pasta', 'pastas']],
  ['gluten-free', 'chapelure', ['chapelure', 'chapelures', 'breadcrumb', 'breadcrumbs', 'pan rallado', 'panes rallados']],
  ['gluten-free', 'panko', ['panko', 'chapelure panko', 'panko', 'panko breadcrumbs', 'panko', 'pan panko']],
  ['gluten-free', 'sauce soja', ['sauce soja', 'sauces soja', 'soy sauce', 'soy sauces', 'salsa de soja', 'salsas de soja']],
  ['gluten-free', 'sauce teriyaki', ['sauce teriyaki', 'sauces teriyaki', 'teriyaki sauce', 'teriyaki sauces', 'salsa teriyaki', 'salsas teriyaki']],
  ['gluten-free', 'bière', ['bière', 'bières', 'beer', 'beers', 'cerveza', 'cervezas']],
  ['gluten-free', 'malt', ['malt', "extrait de malt", 'malt', 'malt vinegar', 'malta', 'maltas']],
  ['gluten-free', 'farine', ['farine', 'farines', 'flour', 'flours', 'harina', 'harinas']],
  ['gluten-free', 'nouilles', ['nouille', 'nouilles', 'noodle', 'noodles', 'fideo', 'fideos']],
  ['gluten-free', 'vermicelles', ['vermicelle', 'vermicelles', 'vermicelli', 'vermicellis', 'fideo fino', 'fideos finos']],
  ['gluten-free', 'spaghetti', ['spaghetti', 'spaghettis', 'spaghetti', 'spaghettis', 'espagueti', 'espaguetis']],
  ['gluten-free', 'macaroni', ['macaroni', 'macaronis', 'macaroni', 'macaronis', 'macarrón', 'macarrones']],
  ['gluten-free', 'lasagnes', ['lasagne', 'lasagnes', 'lasagna', 'lasagnas', 'lasaña', 'lasañas']],
  ['gluten-free', 'tagliatelles', ['tagliatelle', 'tagliatelles', 'tagliatelle', 'tagliatelles', 'tallarín', 'tallarines']],
  ['gluten-free', 'raviolis', ['ravioli', 'raviolis', 'ravioli', 'raviolis', 'ravioli', 'raviolis']],
  ['gluten-free', 'gnocchis', ['gnocchi', 'gnocchis', 'gnocchi', 'gnocchis', 'ñoqui', 'ñoquis']],
  ['gluten-free', 'pâte feuilletée', ['pâte feuilletée', 'pâtes feuilletées', 'puff pastry', 'puff pastries', 'hojaldre', 'hojaldres']],
  ['gluten-free', 'pâte filo', ['feuille de brick', 'feuilles de filo', 'filo pastry', 'phyllo sheets', 'masa filo', 'masas filo']],
  ['gluten-free', 'pâte à pizza', ['pâte à pizza', 'pâtes à pizza', 'pizza dough', 'pizza bases', 'masa de pizza', 'masas de pizza']],
  ['gluten-free', 'pizza', ['pizza', 'pizzas', 'pizza', 'pizzas', 'pizza', 'pizzas']],
  ['gluten-free', 'biscuits', ['biscuit', 'biscuits', 'cookie', 'cookies', 'galleta', 'galletas']],
  ['gluten-free', 'gâteau', ['gâteau', 'gâteaux', 'cake', 'cakes', 'bizcocho', 'bizcochos']],
  ['gluten-free', 'crêpes', ['crêpe', 'crêpes', 'pancake', 'pancakes', 'crepe', 'crepes']],
  ['gluten-free', 'gaufres', ['gaufre', 'gaufres', 'waffle', 'waffles', 'gofre', 'gofres']],
  ['gluten-free', 'tortilla de blé', ['tortilla de blé', 'tortillas de blé', 'flour tortilla', 'flour tortillas', 'tortilla de trigo', 'tortillas de trigo']],
  ['gluten-free', 'croûtons', ['croûton', 'croûtons', 'crouton', 'croutons', 'picatoste', 'picatostes']],
  ['gluten-free', 'seitan', ['seitan', 'seitans', 'seitan', 'seitans', 'seitán', 'seitanes']],
  ['gluten-free', 'empanadas, raviolis chinois', ['empanada', 'empanadas', 'dumpling', 'dumplings', 'empanadilla', 'empanadillas']],
  ['gluten-free', 'biscottes', ['biscotte', 'biscottes', 'cracker', 'crackers', 'galleta salada', 'galletas saladas']],
  ['gluten-free', 'brioche', ['brioche', 'brioches', 'bun', 'buns', 'bollo', 'bollos']],
  ['gluten-free', 'muffins', ['muffin', 'muffins', 'muffin', 'muffins', 'magdalena', 'magdalenas']],
  // ---------- Sans lactose (produits laitiers) ----------
  ['dairy-free', 'lait', ['lait', 'laits', 'milk', 'milks', 'leche', 'leches']],
  ['dairy-free', 'beurre', ['beurre', 'beurres', 'butter', 'butters', 'mantequilla', 'mantequillas']],
  ['dairy-free', 'crème', ['crème', 'crèmes', 'cream', 'creams', 'nata', 'natas']],
  ['dairy-free', 'crème fraîche', ['crème fraîche', 'crèmes fraîches', 'sour cream', 'sour creams', 'crema agria', 'cremas agrias']],
  ['dairy-free', 'chantilly', ['chantilly', 'crème chantilly', 'whipped cream', 'whipped creams', 'nata montada', 'natas montadas']],
  ['dairy-free', 'fromage', ['fromage', 'fromages', 'cheese', 'cheeses', 'queso', 'quesos']],
  ['dairy-free', 'yaourt', ['yaourt', 'yaourts', 'yogurt', 'yogurts', 'yogur', 'yogures']],
  ['dairy-free', 'lactosérum', ['lactosérum', 'petit-lait', 'whey', 'whey powder', 'suero de leche', 'sueros de leche']],
  ['dairy-free', 'babeurre', ['babeurre', 'babeurres', 'buttermilk', 'buttermilks', 'suero de mantequilla', 'sueros de mantequilla']],
  ['dairy-free', 'caséine', ['caséine', 'caséines', 'casein', 'caseins', 'caseína', 'caseínas']],
  ['dairy-free', 'ghee', ['ghee', 'beurre clarifié', 'ghee', 'clarified butter', 'ghee', 'mantequilla clarificada']],
  ['dairy-free', 'kéfir', ['kéfir', 'kéfirs', 'kefir', 'kefirs', 'kéfir', 'kéfires']],
  ['dairy-free', 'fromages frais', ['skyr', 'fromage blanc', 'quark', 'labneh', 'cuajada', 'cuajadas']],
  ['dairy-free', 'parmesan', ['parmesan', 'parmesans', 'parmesan', 'parmigiano', 'parmesano', 'parmesanos']],
  ['dairy-free', 'pecorino', ['pecorino', 'pecorinos', 'pecorino', 'pecorino romano', 'pecorino', 'pecorinos']],
  ['dairy-free', 'mozzarella', ['mozzarella', 'mozzarellas', 'mozzarella', 'burrata', 'mozzarella', 'burratas']],
  ['dairy-free', 'halloumi, paneer', ['halloumi', 'paneer', 'halloumi', 'paneer', 'queso halloumi', 'halloumis']],
  ['dairy-free', 'fromages à pâte pressée', ['gouda', 'goudas', 'edam', 'gruyère', 'manchego', 'manchegos']],
  ['dairy-free', 'fromages à pâte persillée', ['roquefort', 'gorgonzola', 'gorgonzola', 'provolone', 'cabrales', 'gorgonzolas']],
  ['dairy-free', 'ricotta', ['ricotta', 'ricottas', 'ricotta', 'cottage cheese', 'requesón', 'requesones']],
  ['dairy-free', 'mascarpone', ['mascarpone', 'mascarpones', 'mascarpone', 'mascarpones', 'mascarpone', 'mascarpones']],
  ['dairy-free', 'béchamel', ['béchamel', 'béchamels', 'bechamel', 'white sauce', 'bechamel', 'besamel']],
  ['dairy-free', 'crème anglaise', ['crème anglaise', 'crèmes anglaises', 'custard', 'custards', 'natilla', 'natillas']],
  ['dairy-free', 'lait concentré', ['lait concentré', 'laits concentrés', 'condensed milk', 'evaporated milk', 'leche condensada', 'leche evaporada']],
  ['dairy-free', 'desserts lactés', ['riz au lait', 'crème glacée', 'ice cream', 'half and half', 'arroz con leche', 'helado']],
  // ---------- Végétarien (viandes, poissons, fruits de mer, gélatine, bouillons) ----------
  ['vegetarian', 'bœuf', ['bœuf', 'bœufs', 'beef', 'beef cubes', 'ternera', 'carne de res']],
  ['vegetarian', 'veau', ['veau', 'veaux', 'veal', 'veal cutlets', 'carne de ternera', 'terneras']],
  ['vegetarian', 'agneau', ['agneau', 'agneaux', 'lamb', 'lambs', 'cordero', 'corderos']],
  ['vegetarian', 'porc', ['porc', 'côtes de porc', 'pork', 'pork chops', 'cerdo', 'cerdos']],
  ['vegetarian', 'poulet', ['poulet', 'poulets', 'chicken', 'chickens', 'pollo', 'pollos']],
  ['vegetarian', 'dinde', ['dinde', 'dindes', 'turkey', 'turkeys', 'pavo', 'pavos']],
  ['vegetarian', 'canard', ['canard', 'canards', 'duck', 'ducks', 'pato', 'patos']],
  ['vegetarian', 'oie', ['oie', 'oies', 'goose', 'geese', 'ganso', 'gansos']],
  ['vegetarian', 'caille', ['caille', 'cailles', 'quail', 'quails', 'codorniz', 'codornices']],
  ['vegetarian', 'lapin', ['lapin', 'lapins', 'rabbit', 'rabbits', 'conejo', 'conejos']],
  ['vegetarian', 'gibier', ['gibier', 'chevreuil', 'venison', 'venisons', 'venado', 'venados']],
  ['vegetarian', 'jambon', ['jambon', 'jambons', 'ham', 'hams', 'jamón', 'jamones']],
  ['vegetarian', 'lard, bacon', ['lardon', 'lardons', 'bacon', 'bacons', 'beicon', 'tocino']],
  ['vegetarian', 'charcuterie italienne', ['pancetta', 'coppa', 'pancetta', 'prosciutto', 'panceta', 'fiambre']],
  ['vegetarian', 'saucisse', ['saucisse', 'saucisses', 'sausage', 'sausages', 'salchicha', 'salchichas']],
  ['vegetarian', 'chorizo', ['chorizo', 'chorizos', 'chorizo', 'chorizos', 'chorizo', 'chorizos']],
  ['vegetarian', 'saucisses épicées', ['merguez', 'chipolatas', 'hot dog', 'hot dogs', 'longaniza', 'longanizas']],
  ['vegetarian', 'boudin', ['boudin', 'boudins', 'black pudding', 'blood sausage', 'morcilla', 'morcillas']],
  ['vegetarian', 'mortadelle', ['mortadelle', 'mortadelles', 'mortadella', 'mortadellas', 'mortadela', 'mortadelas']],
  ['vegetarian', 'salami', ['salami', 'saucisson', 'salami', 'pepperoni', 'salchichón', 'salchichones']],
  ['vegetarian', 'steak', ['steak', 'steaks', 'steak', 'steaks', 'filete de ternera', 'bistec']],
  ['vegetarian', 'pièces de bœuf', ['entrecôte', 'rumsteck', 'sirloin', 'brisket', 'solomillo', 'solomillos']],
  ['vegetarian', 'côtelettes', ["côtelette d'agneau", 'gigot', 'lamb chop', 'spare ribs', 'chuleta', 'chuletas']],
  ['vegetarian', 'côtes', ['côte de porc', 'travers de porc', 'pork rib', 'short ribs', 'costilla', 'costillas']],
  ['vegetarian', 'blanc, filet', ['escalope de dinde', 'magret', 'chicken breast', 'chicken thighs', 'pechuga', 'pechugas']],
  ['vegetarian', 'cuisse', ['cuisse de poulet', 'aiguillettes de poulet', 'chicken leg', 'chicken wings', 'muslo de pollo', 'muslos']],
  ['vegetarian', 'viande hachée', ['viande hachée', 'boulettes de viande', 'ground beef', 'meatballs', 'carne picada', 'albóndigas']],
  ['vegetarian', 'abats', ['foie', 'foies de volaille', 'liver', 'livers', 'hígado', 'hígados']],
  ['vegetarian', 'tripes', ['gésier', 'gésiers', 'tripe', 'tripes', 'callos', 'mollejas']],
  ['vegetarian', 'plats de viande', ['kebab', 'kebabs', 'nugget', 'nuggets', 'hamburguesa', 'hamburguesas']],
  ['vegetarian', 'graisses animales', ['saindoux', 'graisse de canard', 'lard', 'suet', 'manteca de cerdo', 'grasa de pato']],
  ['vegetarian', 'gélatine', ['gélatine', 'gélatines', 'gelatin', 'gelatins', 'gelatina', 'gelatinas']],
  ['vegetarian', 'gélatine en feuilles', ['grenetine', 'feuilles de gélatine', 'gelatine', 'gelatine sheets', 'láminas de gelatina', 'cola de pescado']],
  ['vegetarian', 'bouillons', ['bouillon de poulet', 'cubes de bouillon', 'chicken stock', 'stock cubes', 'caldo de pollo', 'pastillas de caldo']],
  ['vegetarian', 'fonds et fumets', ['fond de veau', 'fumet de poisson', 'beef broth', 'bone broth', 'caldo de carne', 'consomé']],
  ['vegetarian', 'jus de viande', ['demi-glace', 'jus de viande', 'beef gravy', 'meat juice', 'jugo de carne', 'demi glace']],
  ['vegetarian', 'poisson', ['poisson', 'poissons', 'fish', 'fishes', 'pescado', 'pescados']],
  ['vegetarian', 'saumon', ['saumon', 'saumons', 'salmon', 'salmons', 'salmón', 'salmones']],
  ['vegetarian', 'thon', ['thon', 'thons', 'tuna', 'tunas', 'atún', 'atunes']],
  ['vegetarian', 'cabillaud', ['cabillaud', 'morue', 'cod', 'cods', 'bacalao', 'bacalaos']],
  ['vegetarian', 'merlu', ['merlu', 'merlus', 'hake', 'hakes', 'merluza', 'merluzas']],
  ['vegetarian', 'sardine', ['sardine', 'sardines', 'sardine', 'sardines', 'sardina', 'sardinas']],
  ['vegetarian', 'anchois', ['anchois', 'filets d’anchois', 'anchovy', 'anchovies', 'anchoa', 'boquerones']],
  ['vegetarian', 'maquereau', ['maquereau', 'maquereaux', 'mackerel', 'mackerels', 'caballa', 'caballas']],
  ['vegetarian', 'bar', ['filet de bar', 'loup de mer', 'sea bass', 'sea basses', 'lubina', 'lubinas']],
  ['vegetarian', 'dorade', ['dorade', 'daurades', 'sea bream', 'snapper', 'dorada', 'doradas']],
  ['vegetarian', 'sole', ['filets de sole', 'plie', 'sole fillet', 'plaice', 'lenguado', 'lenguados']],
  ['vegetarian', 'lotte', ['lotte', 'lottes', 'monkfish', 'monkfishes', 'rape', 'rapes']],
  ['vegetarian', 'églefin', ['églefin', 'haddock', 'haddock', 'pollock', 'eglefino', 'abadejo']],
  ['vegetarian', 'colin', ['colin', 'lieu noir', 'whiting', 'coley', 'pescadilla', 'pescadillas']],
  ['vegetarian', 'poissons plats', ['flétan', 'turbot', 'halibut', 'turbot', 'fletán', 'rodaballo']],
  ['vegetarian', 'espadon', ['espadon', 'espadons', 'swordfish', 'catfish', 'pez espada', 'peces']],
  ['vegetarian', 'truite', ['truite', 'truites', 'trout', 'trouts', 'trucha', 'truchas']],
  ['vegetarian', 'tilapia', ['tilapia', 'tilapias', 'tilapia', 'tilapias', 'tilapia', 'mojarras']],
  ['vegetarian', "poissons d'eau douce et d'Afrique", ['capitaine', 'thiof', 'perch', 'carp', 'corvina', 'pargo']],
  ['vegetarian', 'hareng', ['hareng', 'harengs', 'herring', 'herrings', 'arenque', 'arenques']],
  ['vegetarian', 'crevette', ['crevette', 'crevettes', 'shrimp', 'prawns', 'camarón', 'gambas']],
  ['vegetarian', 'langoustine', ['langoustine', 'langoustines', 'langoustine', 'crayfish', 'langostino', 'cigalas']],
  ['vegetarian', 'écrevisse, homard', ['écrevisse', 'écrevisses', 'crawfish', 'lobsters', 'cangrejo de río', 'langostas']],
  ['vegetarian', 'crabe', ['crabe', 'crabes', 'crab', 'crabs', 'cangrejo', 'centollo']],
  ['vegetarian', 'moule', ['moule', 'moules', 'mussel', 'mussels', 'mejillón', 'mejillones']],
  ['vegetarian', 'palourde', ['palourde', 'palourdes', 'clam', 'clams', 'almeja', 'almejas']],
  ['vegetarian', 'coque', ['bulot', 'bulots', 'cockle', 'cockles', 'berberecho', 'berberechos']],
  ['vegetarian', 'huître', ['huître', 'huîtres', 'oyster', 'oysters', 'ostra', 'ostras']],
  ['vegetarian', 'saint-jacques', ['coquille saint-jacques', 'noix de saint-jacques', 'scallop', 'scallops', 'vieira', 'vieiras']],
  ['vegetarian', 'calamar', ['calamar', 'calmars', 'squid', 'calamari', 'calamar', 'chipirones']],
  ['vegetarian', 'seiche', ['encornet', 'encornets', 'cuttlefish', 'squids', 'sepia', 'sepias']],
  ['vegetarian', 'poulpe', ['poulpe', 'pieuvre', 'octopus', 'octopuses', 'pulpo', 'pulpos']],
  ['vegetarian', 'oursin', ['oursin', 'oursins', 'sea urchin', 'sea urchins', 'erizo de mar', 'erizos de mar']],
  ['vegetarian', 'fruits de mer', ['fruits de mer', 'crustacés', 'seafood', 'shellfish', 'marisco', 'mariscos']],
  ['vegetarian', 'œufs de poisson', ['caviar', 'œufs de poisson', 'roe', 'fish eggs', 'huevas', 'caviar']],
  ['vegetarian', 'surimi, anguille', ['surimi', 'anguille', 'surimi', 'eel', 'anguila', 'angulas']],
  ['vegetarian', 'sauces de poisson', ['sauce poisson', 'nuoc-mâm', 'fish sauce', 'oyster sauce', 'salsa de pescado', 'salsa de ostras']],
  ['vegetarian', 'condiments de poisson', ['sauce worcestershire', 'bonite séchée', 'worcestershire sauce', 'dashi', 'bonito', 'bonito seco']],
  // ---------- Vegan (en plus du végétarien) ----------
  ['vegan', 'œuf', ['œuf', 'œufs', 'egg', 'eggs', 'huevo', 'huevos']],
  ['vegan', "jaune, blanc d'œuf", ["jaune d'œuf", "blancs d'œufs", 'egg yolk', 'egg whites', 'yema', 'claras de huevo']],
  ['vegan', 'mayonnaise', ['mayonnaise', 'aïoli', 'mayonnaise', 'aioli', 'mayonesa', 'alioli']],
  ['vegan', 'meringue', ['meringue', 'meringues', 'meringue', 'meringues', 'merengue', 'merengues']],
  ['vegan', 'sauces aux œufs', ['sauce hollandaise', 'sauce béarnaise', 'hollandaise sauce', 'bearnaise sauce', 'salsa holandesa', 'salsa bearnesa']],
  ['vegan', 'miel', ['miel', 'miels', 'honey', 'honeys', 'miel', 'mieles']],
  ['vegan', 'produits laitiers', ['lait', 'beurre', 'milk', 'cheese', 'leche', 'queso']],
  ['vegan', 'viande et poisson', ['poulet', 'thon', 'chicken', 'shrimp', 'pollo', 'gelatina']],
  // ---------- Autres mots ajoutés le 03/10 (un aliment par mot, hors de la grille ci-dessus) ----------
  ['gluten-free', 'pâtisseries et pains du monde', ['beignet', 'beignets', 'bagel', 'pretzels', 'scone', 'donuts']],
  ['gluten-free', 'raviolis asiatiques', ['gyoza', 'gyozas', 'wonton', 'wontons', 'gyoza', 'wonton']],
  ['gluten-free', 'cubes de bouillon (marques)', ['cube Knorr', 'cubes Oxo', 'Knorr stock pot', 'Oxo cubes', 'pastilla Knorr', 'caldo Knorr']],
  ['dairy-free', 'fromages de montagne', ['reblochon', 'tomme de Savoie', 'munster', 'beaufort', 'cancoillotte', 'faisselle']],
  ['dairy-free', 'fromages italiens', ['stracciatella', 'scamorza', 'grana padano', 'stracciatella', 'scamorza fumée', 'grana padano']],
  ['vegetarian', 'gibier', ['cerf', 'sanglier', 'wild boar', 'boar', 'jabalí', 'jabalíes']],
  ['vegetarian', 'charcuterie', ['speck', 'bresaola', 'rillettes', 'saucisse de Strasbourg (knack)', 'cecina', 'andouillette']],
  ['vegetarian', 'saucisses du monde', ['saucisses de Francfort', 'frankfurters', 'bratwurst', 'chistorra', 'butifarra', 'sobrasada']],
  ['vegetarian', 'pièces de viande', ['tournedos', 'chateaubriand', 'paleron', 'faux-filet', 'tenderloin', 'ribeye']],
  ['vegetarian', 'pièces de viande (suite)', ['T-bone', 'rib eye steak', 'beef ribs', 'biftec', 'hamburger', 'hamburgers']],
  ['vegetarian', 'abats', ['rognon', 'rognons', 'gizzards', 'sweetbreads', 'riñón', 'riñones']],
  ['vegetarian', 'graisses et abats (anglais)', ['offal', 'tallow', 'beef tallow', 'beef suet', 'offal', 'tallow']],
  ['vegetarian', 'poissons (compléments)', ['bar de ligne', 'limande', 'lieu jaune', 'merlan', 'brochet', 'perche']],
  ['vegetarian', 'poissons et coquillages (compléments)', ['bigorneaux', 'coquillages', 'tarama', 'whelks', 'codfish', 'whitefish']],
  // ---------- Mot interdit et ingrédient de base qui ne le disculpe pas (non accolés) ----------
  ['vegetarian', 'viande à la sauce soja', ['poulet sauce soja', 'nouilles au poulet et au soja', 'chicken with soy', 'beef and soy sauce', 'pollo con salsa de soja', 'cerdo agridulce soja']],
  ['dairy-free', 'desserts au lait et au riz', ['riz au lait', 'gâteau de riz au lait', 'rice pudding with milk', 'milk and rice', 'arroz con leche', 'leche con arroz y canela']],
];

// Aliments permis qui ne doivent pas être pris pour un aliment interdit
const ALLOWED: [StrictDiet, string[]][] = [
  ['gluten-free', ['trigo sarraceno', 'harina de trigo sarraceno', 'lait de noisette', 'riz', 'farine de riz', 'nouilles de riz', 'vermicelles de riz', 'rice noodles', 'rice flour', 'fideos de arroz', 'harina de arroz', 'farine de maïs', 'semoule de maïs', 'polenta', 'corn tortillas', 'tortillas de maíz', 'sarrasin', 'crêpes de sarrasin', 'buckwheat flour', 'pâtes sans gluten', 'gluten free pasta', 'pasta sin gluten', 'pommes de terre', 'panais', 'parsnip', 'pan-fried tofu', 'quinoa', 'millet', 'tapioca', 'fécule de pomme de terre', 'patate douce', 'pâte de curry', 'pâte de sésame', 'pâte d’arachide', 'tamari', 'pancetta']],
  ['dairy-free', ['lait de riz', 'crème de riz', 'rice milk', 'leche de arroz', 'lait de noisette', 'hazelnut milk', 'oat cream', 'lait d’avoine bio', 'yaourt soja vanille', 'yogur vegano', 'helado vegano', 'lait de coco', 'lait d’amande', 'lait d’avoine', 'oat milk', 'almond milk', 'leche de almendra', 'crème de coco', 'beurre de cacahuète', 'peanut butter', 'mantequilla de cacahuete', 'yaourt au soja', 'yogur de soja', 'fromage végétal', 'vegan cheese', 'butternut', 'courge butternut', 'cream of tartar', 'crème de marrons', 'beurre de karité', 'riz', 'glaçons']],
  ['vegetarian', ['oca andina', 'cerfeuil', 'fumet de légumes', 'barre de céréales aux fruits', 'pâtes coquillettes', 'celery ribs', 'mushroom gravy', 'clementine', 'tomates en grappe', 'steak de soja haché', 'saucisses fumées végétales', 'soy chicken', 'tofu', 'steak de soja', 'saucisse végétale', 'vegetarian sausage', 'bouillon de légumes', 'vegetable stock', 'caldo de verduras', 'champignons', 'pois chiches', 'aubergine', 'pommes de terre', 'pâtes', 'rapeseed oil', 'grapes', 'barre de céréales', 'granola bar', 'sésame', 'carotte', 'pancakes', 'poireaux', 'raisins', 'pêches']],
  ['vegan', ['lait de coco', 'tofu', 'sirop d’érable', 'maple syrup', 'sirope de agave', 'huile d’olive', 'crème de coco', 'beurre de cacahuète']],
];

for (const [diet, food, names] of FORBIDDEN) {
  Deno.test(`régime ${diet} : « ${food} » repéré en trois langues (${names.join(', ')})`, () => {
    assertEquals(names.filter((name) => !dietWordInName(name, diet)), []);
  });
}

for (const [diet, names] of ALLOWED) {
  Deno.test(`régime ${diet} : aliments permis jamais repérés`, () => {
    assertEquals(names.filter((name) => dietWordInName(name, diet)), []);
  });
}

Deno.test('étapes et titres : mots ajoutés ambigus ignorés dans un texte (« plie la crêpe », « sole », « pez »)', () => {
  for (const text of ['Plie la crêpe en quatre.', 'Pan-fry the tofu until golden.', 'Mezcla la masa y añade una pizca de sal.']) {
    assertEquals(dietWordInText(text, 'vegetarian'), false);
  }
  assertEquals(dietWordInText('Ajoute les lardons.', 'vegetarian'), true);
  assertEquals(dietWordInText('Sirve con queso manchego.', 'dairy-free'), true);
});
